repos: 
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    - id: flake8
      args: ['--config=setup.cfg --ignore=E203,W503']
