name: student-project-timmens

channels:
- conda
- conda-forge
- r

dependencies:
- numpy
- pandas
- black 
- flake8
- scipy=1.2.1
- scikit-learn
- seaborn 
- jupyterlab
- matplotlib
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- pip
- pip:
  - graphviz 
- graphviz
- r-essentials
- rpy2
